# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368bf812a6759d3b9a96aeac5cb365b048c9b29adb0df16d1abeb94e369cd0bad2d26cc2fb0ece058ec9065851ee584936cdc0172d908c87642935f4212db0d6

test:
  secret_key_base: 834397efadf1350e3521e022a4573907b1ff1ab2078f7b1bd517e4451c624ca2216fb648c6ad8ba914480c6eaefb727db9b5f28a05082c703cb7d912bd70ce3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
